#!/usr/bin/env node
// Purposeful cover generator for the mishmash-assets design library (PRD C5).
//
// Every catalog item should get a cover that accurately shows what it
// contains, instead of a random bundled image or a tiny contact sheet:
//   - ui-kit / design-system items -> a kit reconstruction sheet: 1-5 of the
//     kit's own strongest screens (rendered live when the kit ships static
//     HTML, else its own bundled preview imagery, else the Figma-embedded
//     thumbnail), composed on a quiet dark studio surface.
//   - icons items -> an even grid of the set's own individual icon files.
//   - any item with no usable content at all falls back to a typographic
//     cover: name + category + file-type chips, never blank.
//
// catalog.json's `category`/`description` fields were hand-classified in an
// earlier task (see scripts/design-taxonomy.ts). build_catalog.py in
// mishmash-assets/.catalog REGENERATES those fields from folder names on
// every run, so this script never invokes it — it writes thumbs on disk and
// patches only the `thumb` field of processed catalog.json items directly.
//
// Usage:
//   node scripts/generate-library-covers.ts [--only <category|id>]
//
// The mishmash-assets checkout defaults to the maintainer's path; set
// OD_MISHMASH_ASSETS_DIR to point at a checkout under a different home.

import * as fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

import { CATEGORY_LABELS } from './design-taxonomy.ts';

// ---------------------------------------------------------------------------
// Minimal structural Playwright types. The `playwright` package is a
// dependency of apps/daemon (and e2e), not of the repo root, so pnpm's
// workspace linking only makes it resolvable — and its types importable —
// from there. Loading it below goes through `createRequire` + a dynamic
// `import()` for exactly that reason; these types describe only the surface
// this script actually calls.
// ---------------------------------------------------------------------------
type PlaywrightPage = {
  setViewportSize(size: { width: number; height: number }): Promise<void>;
  goto(url: string, options?: { waitUntil?: string; timeout?: number }): Promise<unknown>;
  evaluate<T>(fn: () => T | Promise<T>): Promise<T>;
  evaluate<T, A>(fn: (arg: A) => T | Promise<T>, arg: A): Promise<T>;
  waitForTimeout(ms: number): Promise<void>;
  screenshot(options: { path: string; type?: string; quality?: number }): Promise<Buffer>;
};
type PlaywrightBrowser = {
  newPage(): Promise<PlaywrightPage>;
  close(): Promise<void>;
};
type PlaywrightChromium = {
  launch(): Promise<PlaywrightBrowser>;
};
type PlaywrightModule = { chromium: PlaywrightChromium };

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(SCRIPT_DIR, '..');
const nodeRequire = createRequire(import.meta.url);
const playwrightEntry = nodeRequire.resolve('playwright', { paths: [path.join(REPO_ROOT, 'apps/daemon')] });
const importedPlaywright = (await import(pathToFileURL(playwrightEntry).href)) as
  | PlaywrightModule
  | { default: PlaywrightModule };
const { chromium } = 'default' in importedPlaywright ? importedPlaywright.default : importedPlaywright;

const ASSETS_ROOT = process.env.OD_MISHMASH_ASSETS_DIR?.trim()
  ? path.resolve(process.env.OD_MISHMASH_ASSETS_DIR)
  : '/Users/zero-suminc./projects/mishmash-assets';
const CATALOG_PATH = path.join(ASSETS_ROOT, 'catalog.json');
const THUMBS_DIR = path.join(ASSETS_ROOT, '.catalog', 'thumbs');
const META_DIR = path.join(THUMBS_DIR, '.generate-covers-meta');
const BACKUP_DIR = path.join(os.homedir(), 'Backups', 'mishmash');
const BACKUP_PATH = path.join(BACKUP_DIR, 'catalog-pre-t5.json');
const TMP_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'mm-covers-'));

const KIT_CATEGORIES = new Set(['ui-kit', 'design-system']);

const SKIP_DIRS = new Set([
  '_zips', '_inbox', '_quarantine', '.git', 'node_modules', '.next', '.catalog',
  '__MACOSX', '_quarantine-html', 'duplicates', 'dist', '.turbo', 'coverage', '.cache',
]);
const RASTER_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp']);
const PREF_RE = /preview|cover|hero|home|main|screenshot|dashboard|landing|index/i;
const NEG_RE = /logo|favicon|sprite|avatar|badge|placeholder|spacer/i;

// The mishmash-assets catalog schema this script relies on. It is external
// data (regenerated by build_catalog.py), so fields beyond what this script
// reads/writes are intentionally not modeled.
interface CatalogItem {
  id: string;
  category: string;
  label: string;
  rel: string;
  kind?: string;
  thumb?: string;
  cover_policy?: unknown;
  description?: string;
}
type CatalogGroup = { items?: CatalogItem[] };
type CatalogData = { groups?: CatalogGroup[] };

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

function walkFiles(dir: string, { maxFiles = 6000, maxDepth = 10 } = {}): string[] {
  const out: string[] = [];
  function visit(d: string, depth: number): void {
    if (depth > maxDepth || out.length >= maxFiles) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (out.length >= maxFiles) return;
      if (e.name.startsWith('.')) continue;
      if (e.isDirectory()) {
        if (SKIP_DIRS.has(e.name)) continue;
        visit(path.join(d, e.name), depth + 1);
      } else if (e.isFile()) {
        out.push(path.join(d, e.name));
      }
    }
  }
  visit(dir, 0);
  return out;
}

type RasterCandidate = { path: string; size: number; name: string };

function findRasterCandidates(dir: string): RasterCandidate[] {
  const files = walkFiles(dir);
  const rasters: RasterCandidate[] = [];
  for (const f of files) {
    const ext = path.extname(f).toLowerCase();
    if (!RASTER_EXT.has(ext)) continue;
    let size: number;
    try {
      size = fs.statSync(f).size;
    } catch {
      continue;
    }
    if (size < 20 * 1024) continue; // skip spacer/icon-sized files
    rasters.push({ path: f, size, name: path.basename(f) });
  }
  rasters.sort((a, b) => {
    const aPref = PREF_RE.test(a.name) && !NEG_RE.test(a.name) ? 1 : 0;
    const bPref = PREF_RE.test(b.name) && !NEG_RE.test(b.name) ? 1 : 0;
    if (aPref !== bPref) return bPref - aPref;
    const aNeg = NEG_RE.test(a.name) ? 1 : 0;
    const bNeg = NEG_RE.test(b.name) ? 1 : 0;
    if (aNeg !== bNeg) return aNeg - bNeg;
    return b.size - a.size;
  });
  return rasters;
}

type SizedFile = { path: string; size: number };

function findFigFiles(dir: string): SizedFile[] {
  return walkFiles(dir)
    .filter((f) => f.toLowerCase().endsWith('.fig'))
    .map((f) => ({ path: f, size: fs.statSync(f).size }))
    .sort((a, b) => b.size - a.size);
}

function extractFigThumbnail(figPath: string): string | null {
  try {
    const listing = execFileSync('unzip', ['-l', figPath], { encoding: 'utf8', maxBuffer: 20 * 1024 * 1024 });
    const line = listing.split('\n').find((l) => /thumbnail\.png$/i.test(l.trim()));
    if (!line) return null;
    const entry = line.trim().split(/\s+/).slice(3).join(' ');
    const buf = execFileSync('unzip', ['-p', figPath, entry], { maxBuffer: 50 * 1024 * 1024 });
    const tmp = path.join(TMP_DIR, `fig-thumb-${crypto.randomUUID()}.png`);
    fs.writeFileSync(tmp, buf);
    return tmp;
  } catch {
    return null;
  }
}

function findHtmlCandidates(dir: string): string[] {
  const files = walkFiles(dir).filter((f) => f.toLowerCase().endsWith('.html'));
  const filtered = files.filter((f) => {
    const base = path.basename(f).toLowerCase();
    if (base === '404.html' || base === 'sitemap.html') return false;
    if (f.toLowerCase().includes(`${path.sep}documentation${path.sep}`)) return false;
    return true;
  });
  const score = (f: string): number => {
    const base = path.basename(f).toLowerCase();
    // Named demo variants (index-creative-agency.html) are real pages; a bare
    // index.html is often just a template picker/hub for multi-demo kits, so
    // it ranks below named variants but above unrelated interior pages.
    if (/^(index|home|landing|main)-.+\.html$/.test(base)) return 2;
    if (base === 'index.html' || base === 'home.html' || base === 'landing.html' || base === 'main.html') return 1;
    return 0;
  };
  filtered.sort((a, b) => score(b) - score(a));
  return filtered;
}

function findZipFiles(dir: string): SizedFile[] {
  return walkFiles(dir)
    .filter((f) => f.toLowerCase().endsWith('.zip'))
    .map((f) => ({ path: f, size: fs.statSync(f).size }))
    .sort((a, b) => b.size - a.size);
}

function extractBestImageFromZip(zipPath: string): string | null {
  try {
    const listing = execFileSync('unzip', ['-l', zipPath], { encoding: 'utf8', maxBuffer: 20 * 1024 * 1024 });
    const candidates: { entry: string; size: number }[] = [];
    for (const line of listing.split('\n')) {
      const m = line.trim().match(/^(\d+)\s+\S+\s+\S+\s+(.+)$/);
      if (!m) continue;
      const size = parseInt(m[1] ?? '0', 10);
      const entry = m[2] ?? '';
      if (!/\.(png|jpe?g|webp)$/i.test(entry)) continue;
      if (size < 20 * 1024) continue;
      candidates.push({ entry, size });
    }
    candidates.sort((a, b) => {
      const aPref = PREF_RE.test(a.entry) && !NEG_RE.test(a.entry) ? 1 : 0;
      const bPref = PREF_RE.test(b.entry) && !NEG_RE.test(b.entry) ? 1 : 0;
      if (aPref !== bPref) return bPref - aPref;
      return b.size - a.size;
    });
    const best = candidates[0];
    if (!best) return null;
    const buf = execFileSync('unzip', ['-p', zipPath, best.entry], { maxBuffer: 50 * 1024 * 1024 });
    const ext = path.extname(best.entry) || '.png';
    const tmp = path.join(TMP_DIR, `zip-img-${crypto.randomUUID()}${ext}`);
    fs.writeFileSync(tmp, buf);
    return tmp;
  } catch {
    return null;
  }
}

// `sips` (already used for resizing above) also reports pixel dimensions
// without decoding the file in-process — used to floor-check a would-be hero
// image before committing to it, the same way MIN_TILE_DIM floors sliced
// contact-sheet tiles.
function getImagePixelDimensions(imgPath: string): { width: number; height: number } | null {
  try {
    const out = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', imgPath], { encoding: 'utf8' });
    const width = Number(/pixelWidth:\s*(\d+)/.exec(out)?.[1]);
    const height = Number(/pixelHeight:\s*(\d+)/.exec(out)?.[1]);
    if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) return null;
    return { width, height };
  } catch {
    return null;
  }
}

function extensionHistogram(dir: string): [string, number][] {
  const counts = new Map<string, number>();
  for (const f of walkFiles(dir, { maxFiles: 3000 })) {
    const ext = path.extname(f).toLowerCase() || '(no ext)';
    counts.set(ext, (counts.get(ext) || 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]);
}

function toDataUri(imgPath: string, { maxDim = 900 } = {}): string | null {
  const ext = path.extname(imgPath).toLowerCase();
  let srcPath = imgPath;
  let mime = ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg';
  try {
    const size = fs.statSync(imgPath).size;
    if (size > 300 * 1024) {
      const tmp = path.join(TMP_DIR, `resized-${crypto.randomUUID()}.jpg`);
      execFileSync('sips', ['-s', 'format', 'jpeg', '-Z', String(maxDim), imgPath, '--out', tmp], { stdio: 'ignore' });
      if (fs.existsSync(tmp)) {
        srcPath = tmp;
        mime = 'image/jpeg';
      }
    }
  } catch {
    // fall back to reading the original file below
  }
  try {
    const buf = fs.readFileSync(srcPath);
    if (buf.length > 6 * 1024 * 1024) return null; // guard against runaway HTML payloads
    return `data:${mime};base64,${buf.toString('base64')}`;
  } catch {
    return null;
  }
}

function readSvgInline(svgPath: string): string | null {
  try {
    let text = fs.readFileSync(svgPath, 'utf8');
    if (text.length > 200 * 1024) return null;
    text = text.replace(/<\?xml[^>]*\?>/, '').trim();
    if (!/^<svg/i.test(text)) return null;
    return text;
  } catch {
    return null;
  }
}

const HTML_ESCAPES: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };

function escapeHtml(str: unknown): string {
  return String(str).replace(/[&<>"']/g, (c) => HTML_ESCAPES[c] ?? c);
}

// ---------------------------------------------------------------------------
// Studio-surface HTML composition
// ---------------------------------------------------------------------------

const BASE_STYLE = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { width: 1600px; height: 1000px; overflow: hidden; background: #0a0a0c;
    font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif; }
  .canvas { position: relative; width: 1600px; height: 1000px; background:
    radial-gradient(ellipse at 50% -10%, rgba(255,255,255,0.05), transparent 60%),
    radial-gradient(ellipse at 50% 112%, rgba(0,0,0,0.65), transparent 60%),
    #0b0b0d; }
  .frame { position: absolute; border-radius: 14px; overflow: hidden; background-size: cover;
    background-position: center top; box-shadow: 0 20px 60px rgba(0,0,0,0.55);
    border: 1px solid rgba(255,255,255,0.07); }
  .caption { color: rgba(255,255,255,0.92); font-weight: 600; letter-spacing: -0.01em; }
  .chip { display: inline-flex; align-items: center; padding: 6px 14px; border-radius: 999px;
    background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.12);
    color: rgba(255,255,255,0.68); font-size: 15px; font-weight: 500; white-space: nowrap; }
`;

function page(bodyInner: string, extraStyle = ''): string {
  return `<!doctype html><html><head><meta charset="utf-8"><style>${BASE_STYLE}${extraStyle}</style></head><body>${bodyInner}</body></html>`;
}

// `CATEGORY_LABELS[category] || category` — falls back to the raw category
// string itself (never undefined here: every call site supplies a category).
function categoryLabelFor(category: string): string {
  return CATEGORY_LABELS[category] || category;
}

function composeKitSheetHtml({
  label,
  categoryLabel,
  screens,
  captionNote,
}: {
  label: string;
  categoryLabel: string;
  screens: string[];
  captionNote: string | null;
}): string {
  const heroOnly = screens.length === 1;
  const heroHeight = heroOnly ? 800 : 620;
  let supporting = '';
  if (!heroOnly) {
    const n = screens.length - 1;
    const gap = 20;
    const w = Math.floor((1488 - gap * (n - 1)) / n);
    supporting = screens
      .slice(1)
      .map((s, i) => {
        const x = 56 + i * (w + gap);
        return `<div class="frame" style="left:${x}px; top:700px; width:${w}px; height:220px; background-image:url('${s}');"></div>`;
      })
      .join('');
  }
  const count = screens.length;
  const note = captionNote || `${count} screen${count > 1 ? 's' : ''}`;
  return page(`
    <div class="canvas">
      <div class="frame" style="left:56px; top:56px; width:1488px; height:${heroHeight}px; background-image:url('${screens[0]}');"></div>
      ${supporting}
      <div style="position:absolute; left:56px; top:936px; right:56px; display:flex; align-items:center; justify-content:space-between;">
        <div class="caption" style="font-size:28px;">${escapeHtml(label)}</div>
        <div style="display:flex; gap:10px;">
          <span class="chip">${escapeHtml(categoryLabel)}</span>
          <span class="chip">${escapeHtml(note)}</span>
        </div>
      </div>
    </div>`);
}

type IconCell = { svg?: string; dataUri?: string };

function composeIconGridHtml({
  label,
  categoryLabel,
  icons,
  cols,
  rows,
}: {
  label: string;
  categoryLabel: string;
  icons: IconCell[];
  cols: number;
  rows: number;
}): string {
  const gap = 20;
  const top = 130;
  const bottom = 60;
  const totalW = 1488;
  const totalH = 1000 - top - bottom;
  const cellW = Math.floor((totalW - gap * (cols - 1)) / cols);
  const cellH = Math.floor((totalH - gap * (rows - 1)) / rows);
  const cells = icons
    .map((icon, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = 56 + col * (cellW + gap);
      const y = top + row * (cellH + gap);
      const inner = icon.svg
        ? `<div style="width:56%; height:56%; display:flex; align-items:center; justify-content:center;">${icon.svg}</div>`
        : `<img src="${icon.dataUri}" style="width:56%; height:56%; object-fit:contain;" />`;
      return `<div style="position:absolute; left:${x}px; top:${y}px; width:${cellW}px; height:${cellH}px; background:#f4f3ef; border-radius:16px; display:flex; align-items:center; justify-content:center; box-shadow:0 8px 20px rgba(0,0,0,0.35);">${inner}</div>`;
    })
    .join('');
  return page(
    `
    <div class="canvas">
      <div style="position:absolute; left:56px; top:48px; right:56px; display:flex; align-items:center; justify-content:space-between;">
        <div class="caption" style="font-size:30px;">${escapeHtml(label)}</div>
        <div style="display:flex; gap:10px;">
          <span class="chip">${escapeHtml(categoryLabel)}</span>
          <span class="chip">${icons.length} icons</span>
        </div>
      </div>
      ${cells}
    </div>`,
    'svg { width: 100%; height: 100%; display: block; }',
  );
}

function composeHeroCoverHtml({
  label,
  categoryLabel,
  dataUri,
}: {
  label: string;
  categoryLabel: string;
  dataUri: string;
}): string {
  return page(`
    <div class="canvas">
      <div style="position:absolute; inset:0; background-image:url('${dataUri}'); background-size:cover; background-position:center;"></div>
      <div style="position:absolute; inset:0; background:linear-gradient(to top, rgba(6,6,8,0.88) 0%, rgba(6,6,8,0.35) 42%, transparent 66%);"></div>
      <div style="position:absolute; left:56px; right:56px; bottom:48px; display:flex; align-items:flex-end; justify-content:space-between;">
        <div class="caption" style="font-size:32px;">${escapeHtml(label)}</div>
        <span class="chip">${escapeHtml(categoryLabel)}</span>
      </div>
    </div>`);
}

function composeFallbackHtml({
  label,
  categoryLabel,
  kindLabel,
  extChips,
}: {
  label: string;
  categoryLabel: string;
  kindLabel: string;
  extChips: [string, number][];
}): string {
  const chips = extChips.map(([ext, count]) => `<span class="chip">${escapeHtml(ext)} × ${count}</span>`).join('');
  return page(`
    <div class="canvas" style="display:flex; align-items:center; justify-content:center;">
      <div style="text-align:center; max-width:1200px;">
        <div style="font-size:52px; font-weight:700; color:rgba(255,255,255,0.95); letter-spacing:-0.02em; margin-bottom:22px;">${escapeHtml(label)}</div>
        <div style="display:flex; gap:12px; justify-content:center; flex-wrap:wrap; margin-bottom:18px;">
          <span class="chip">${escapeHtml(categoryLabel)}</span>
          <span class="chip">${escapeHtml(kindLabel)}</span>
        </div>
        <div style="display:flex; gap:10px; justify-content:center; flex-wrap:wrap;">${chips}</div>
      </div>
    </div>`);
}

function composeFallbackFor(item: CatalogItem, dir: string): string {
  const hist = extensionHistogram(dir).slice(0, 4);
  const chips: [string, number][] = hist.length ? hist : [[item.kind || 'no preview', 1]];
  return composeFallbackHtml({
    label: item.label,
    categoryLabel: categoryLabelFor(item.category),
    kindLabel: item.kind || 'No preview',
    extChips: chips,
  });
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

// `page.evaluate()` callbacks run inside the browser page, not this Node
// process — `window`/`document`/`Image`/canvas are real there, but
// scripts/tsconfig.json's lib is Node-only (no "DOM"). These module-scoped
// ambient declarations type only the handful of browser globals the
// callbacks below actually touch, without pulling the DOM lib into every
// other script under scripts/.
type CanvasContext2D = {
  drawImage(img: ImageLike | CanvasLike, dx: number, dy: number): void;
  drawImage(
    img: ImageLike | CanvasLike,
    sx: number,
    sy: number,
    sw: number,
    sh: number,
    dx: number,
    dy: number,
    dw: number,
    dh: number,
  ): void;
  getImageData(sx: number, sy: number, sw: number, sh: number): { data: Uint8ClampedArray };
};
type CanvasLike = {
  width: number;
  height: number;
  getContext(kind: '2d'): CanvasContext2D | null;
  toDataURL(type?: string, quality?: number): string;
};
type ImageLike = {
  onload: (() => void) | null;
  onerror: (() => void) | null;
  src: string;
  naturalWidth: number;
  naturalHeight: number;
};
declare class Image implements ImageLike {
  onload: (() => void) | null;
  onerror: (() => void) | null;
  src: string;
  naturalWidth: number;
  naturalHeight: number;
}
declare const window: { innerHeight: number; scrollTo(x: number, y: number): void };
declare const document: {
  body: { scrollHeight: number };
  createElement(tag: 'canvas'): CanvasLike;
};

// ---------------------------------------------------------------------------
// Contact-sheet detection & tile extraction
//
// Some Figma-only kits (e.g. "62 screens", "Ai personal health") have no
// bundled preview image of their own — the only thing available is the
// .fig file's embedded `thumbnail.png`, which for a many-frame canvas is
// Figma's render of the WHOLE canvas: a grid of dozens of small tiles. Using
// that directly as a hero is exactly the "tiny blurry contact sheet" the PRD
// forbids. The same shape can occur from a single bundled raster preview
// too. Detect the grid and slice it into individual tiles so the composed
// cover shows a handful of screens at legible size instead.
// ---------------------------------------------------------------------------

type SheetTileRaw = { x: number; y: number; w: number; h: number; dataUri: string; byteLen: number };
type SheetAnalysisRaw = { cols: number; rows: number; tiles: SheetTileRaw[] } | null;

// Runs inside the Playwright page (browser context), not Node — see the
// ambient DOM declarations above. Pragmatic heuristic, not real computer
// vision: sample columns/rows for the fraction of pixels matching the
// dominant background color, treat long near-100%-background runs as
// gutters, and require the resulting tile grid to be at least 2x3 and
// reasonably uniform in size before calling it a sheet. A genuine
// single-screen preview (the common case) fails one of those checks and
// returns null, leaving the original image untouched.
async function sheetAnalysisBrowserFn(srcDataUri: string): Promise<SheetAnalysisRaw> {
  const img = new Image();
  const loaded = new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error('image failed to load'));
  });
  img.src = srcDataUri;
  await loaded;
  const w = img.naturalWidth;
  const h = img.naturalHeight;
  if (!w || !h) return null;
  if (w * h > 20_000_000) return null; // guard against runaway analysis on huge sources

  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  ctx.drawImage(img, 0, 0);
  const { data } = ctx.getImageData(0, 0, w, h);

  const pixelAt = (x: number, y: number): [number, number, number] => {
    const i = (y * w + x) * 4;
    return [data[i] ?? 0, data[i + 1] ?? 0, data[i + 2] ?? 0];
  };

  // Dominant background color from a coarse sample grid (more robust than
  // trusting a single corner, which can itself sit on a tile).
  const votes = new Map<string, number>();
  const grid = 24;
  for (let gy = 0; gy < grid; gy++) {
    for (let gx = 0; gx < grid; gx++) {
      const x = Math.min(w - 1, Math.floor((gx / grid) * w));
      const y = Math.min(h - 1, Math.floor((gy / grid) * h));
      const [r, g, b] = pixelAt(x, y);
      const key = `${Math.round(r / 8) * 8},${Math.round(g / 8) * 8},${Math.round(b / 8) * 8}`;
      votes.set(key, (votes.get(key) ?? 0) + 1);
    }
  }
  let bg: [number, number, number] = [0, 0, 0];
  let bestVotes = -1;
  for (const [key, count] of votes) {
    if (count > bestVotes) {
      bestVotes = count;
      const parts = key.split(',').map(Number);
      bg = [parts[0] ?? 0, parts[1] ?? 0, parts[2] ?? 0];
    }
  }
  const closeToBg = (p: [number, number, number], tol = 16): boolean =>
    Math.abs(p[0] - bg[0]) <= tol && Math.abs(p[1] - bg[1]) <= tol && Math.abs(p[2] - bg[2]) <= tol;

  const colStepY = Math.max(1, Math.floor(h / 260));
  const colBgFrac: number[] = new Array(w).fill(0);
  let sampledRows = 0;
  for (let y = 0; y < h; y += colStepY) {
    sampledRows++;
    for (let x = 0; x < w; x++) {
      if (closeToBg(pixelAt(x, y))) colBgFrac[x] = (colBgFrac[x] ?? 0) + 1;
    }
  }
  for (let x = 0; x < w; x++) colBgFrac[x] = (colBgFrac[x] ?? 0) / Math.max(1, sampledRows);

  const rowStepX = Math.max(1, Math.floor(w / 260));
  const rowBgFrac: number[] = new Array(h).fill(0);
  let sampledCols = 0;
  for (let x = 0; x < w; x += rowStepX) {
    sampledCols++;
    for (let y = 0; y < h; y++) {
      if (closeToBg(pixelAt(x, y))) rowBgFrac[y] = (rowBgFrac[y] ?? 0) + 1;
    }
  }
  for (let y = 0; y < h; y++) rowBgFrac[y] = (rowBgFrac[y] ?? 0) / Math.max(1, sampledCols);

  const findRuns = (frac: number[], threshold: number, minRun: number): [number, number][] => {
    const runs: [number, number][] = [];
    let start: number | null = null;
    for (let i = 0; i < frac.length; i++) {
      const isGutter = (frac[i] ?? 0) >= threshold;
      if (!isGutter) {
        if (start === null) start = i;
      } else if (start !== null) {
        if (i - start >= minRun) runs.push([start, i]);
        start = null;
      }
    }
    if (start !== null && frac.length - start >= minRun) runs.push([start, frac.length]);
    return runs;
  };

  const colRuns = findRuns(colBgFrac, 0.88, Math.max(12, Math.floor(w * 0.015)));
  const rowRuns = findRuns(rowBgFrac, 0.88, Math.max(12, Math.floor(h * 0.015)));
  const cols = colRuns.length;
  const rows = rowRuns.length;
  if (cols < 2 || rows < 2 || cols * rows < 6 || cols * rows > 200) return null;

  // Regularity: a real screen grid has near-uniform tile sizes. A row of
  // unrelated content blobs (not a grid) will not.
  const widths = colRuns.map(([a, b]) => b - a);
  const heights = rowRuns.map(([a, b]) => b - a);
  const mean = (arr: number[]): number => arr.reduce((s, v) => s + v, 0) / arr.length;
  const stdev = (arr: number[], m: number): number => Math.sqrt(mean(arr.map((v) => (v - m) ** 2)));
  const wMean = mean(widths);
  const hMean = mean(heights);
  if (wMean <= 0 || hMean <= 0) return null;
  if (stdev(widths, wMean) / wMean > 0.35 || stdev(heights, hMean) / hMean > 0.35) return null;

  const tiles: SheetTileRaw[] = [];
  for (const rowRun of rowRuns) {
    const [ry0, ry1] = rowRun;
    for (const colRun of colRuns) {
      const [cx0, cx1] = colRun;
      const tw = cx1 - cx0;
      const th = ry1 - ry0;
      if (tw < 20 || th < 20) continue;
      const tileCanvas = document.createElement('canvas');
      tileCanvas.width = tw;
      tileCanvas.height = th;
      const tileCtx = tileCanvas.getContext('2d');
      if (!tileCtx) continue;
      tileCtx.drawImage(canvas, cx0, ry0, tw, th, 0, 0, tw, th);
      const dataUri = tileCanvas.toDataURL('image/jpeg', 0.85);
      tiles.push({ x: cx0, y: ry0, w: tw, h: th, dataUri, byteLen: dataUri.length });
    }
  }
  if (tiles.length < 3) return null;
  return { cols, rows, tiles };
}

function readRawDataUri(imgPath: string): string | null {
  try {
    const ext = path.extname(imgPath).toLowerCase();
    const mime = ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg';
    const buf = fs.readFileSync(imgPath);
    if (buf.length > 15 * 1024 * 1024) return null; // guard against pathological sources
    return `data:${mime};base64,${buf.toString('base64')}`;
  } catch {
    return null;
  }
}

function writeDataUriToFile(dataUri: string, outPath: string): boolean {
  const match = /^data:[^;]+;base64,(.+)$/s.exec(dataUri);
  const base64 = match?.[1];
  if (!base64) return false;
  try {
    fs.writeFileSync(outPath, Buffer.from(base64, 'base64'));
    return true;
  } catch {
    return false;
  }
}

// A many-frame .fig's embedded thumbnail.png is Figma-generated and capped
// at roughly 400px on its long edge regardless of the source file — this is
// a platform limit, not something this script controls. Sliced into even a
// modest grid, individual tiles land well under 100px on a side: no amount
// of grid-detection accuracy fixes that, so a detected tile smaller than
// this floor is refused rather than blown up into a blurry hero/thumbnail.
const MIN_TILE_DIM = 140;

// Empirically (live-app review, 2026-08-10), pure pixel gutter-detection is
// unreliable on this dataset: it missed both known contact sheets ("62
// screens", "Ai personal health" — their grids are irregular/over-fragmented
// at 400px) and produced false positives on genuinely single-hero
// promotional images ("Aura finance widgets", "Ventr") whose incidental
// dark-background composition coincidentally resembled a regular grid,
// yielding badly upscaled blurry crops — a worse defect than the one being
// fixed. The catalog's human-curated `description` field was written by
// directly reading each kit's actual thumbnail, so explicit density
// language ("dense tile of ... screens", "62 tiled ... screens", "40+
// screens", "dozens of ... screens") is a precise, zero-guesswork signal
// that pixel analysis could not reliably reconstruct. Pixel slicing is kept
// as a secondary confirmation step (gated by this text signal, and by
// MIN_TILE_DIM below) rather than the primary detector.
const DENSE_SHEET_RE =
  /\b\d+\+?\s+(tiled\s+)?screens?\b|\btiled\b[^.]{0,40}\bscreens?\b|\bdense\s+(tile|grid)\s+of\b[^.]{0,60}\bscreens?\b|\bdozens\s+of\b[^.]{0,30}\bscreens?\b/i;
const SHEET_NEGATION_RE = /\bnot\b[^.]{0,25}\bscreens?\b|\bscreens?\b[^.]{0,10}\bnot\b/i;

// "Ai personal health" was confirmed by direct visual inspection (Read on
// the current .jpg during the C5 follow-up) to be a dense multi-screen
// contact sheet, even though its curated description doesn't use
// "dense/tiled/dozens" language the automatic text gate matches on.
const KNOWN_CONTACT_SHEET_IDS = new Set<string>(['01-ui8-kits-ai-personal-health']);

function looksLikeDenseSheet(item: CatalogItem): boolean {
  if (KNOWN_CONTACT_SHEET_IDS.has(item.id)) return true;
  const text = `${item.label} ${item.description ?? ''}`;
  return DENSE_SHEET_RE.test(text) && !SHEET_NEGATION_RE.test(text);
}

type SheetRemediation = {
  screens: string[];
  captionNote: string;
  galleryTiles: string[]; // data URIs, up to 4, for the daemon gallery strip
  grid: { cols: number; rows: number; totalTiles: number };
};

// Attempts to detect+slice a contact sheet at `imgPath`, ONLY for images the
// caller has already confirmed are dense sheets via `looksLikeDenseSheet`.
// Returns null when no clean-enough grid is found, or when the detected
// tiles fall under MIN_TILE_DIM — in both cases the caller must not use the
// source image at all (see the fig-thumbnail call site: it downgrades to
// the typographic fallback rather than risk a tiny/blurry cover).
async function tryRemediateContactSheet(pageObj: PlaywrightPage, imgPath: string): Promise<SheetRemediation | null> {
  const rawDataUri = readRawDataUri(imgPath);
  if (!rawDataUri) return null;
  let analysis: SheetAnalysisRaw;
  try {
    analysis = await pageObj.evaluate<SheetAnalysisRaw, string>(sheetAnalysisBrowserFn, rawDataUri);
  } catch {
    return null;
  }
  if (!analysis) return null;
  const ranked = [...analysis.tiles].sort((a, b) => b.byteLen - a.byteLen);
  const top = ranked.slice(0, 5);
  if (top.length < 3) return null;
  const avgW = top.reduce((sum, t) => sum + t.w, 0) / top.length;
  const avgH = top.reduce((sum, t) => sum + t.h, 0) / top.length;
  if (avgW < MIN_TILE_DIM || avgH < MIN_TILE_DIM) return null;
  return {
    screens: top.map((t) => t.dataUri),
    captionNote: `${analysis.cols}×${analysis.rows} screens (sliced)`,
    galleryTiles: top.slice(1, 5).map((t) => t.dataUri),
    grid: { cols: analysis.cols, rows: analysis.rows, totalTiles: analysis.tiles.length },
  };
}

async function screenshotHtmlFile(
  page_: PlaywrightPage,
  htmlPath: string,
  outPngPath: string,
  { width = 1280, height = 800 } = {},
): Promise<void> {
  await page_.setViewportSize({ width, height });
  await page_.goto(pathToFileURL(htmlPath).href, { waitUntil: 'networkidle', timeout: 15000 }).catch(() => {});
  // Many templates lazy-load hero imagery via IntersectionObserver, which
  // never fires unless the page has actually scrolled. Nudge it, then settle
  // a few pixels below true top (not exactly 0) — some templates gate their
  // hero reveal on having scrolled at all, and a few px is enough to cross
  // that threshold without leaving the frame visibly scrolled.
  await page_
    .evaluate(async () => {
      const step = Math.max(window.innerHeight, 400);
      const max = Math.min(document.body.scrollHeight, step * 6);
      for (let y = 0; y <= max; y += step) {
        window.scrollTo(0, y);
        await new Promise((r) => setTimeout(r, 120));
      }
      window.scrollTo(0, 24);
      await new Promise((r) => setTimeout(r, 150));
    })
    .catch(() => {});
  await page_.waitForTimeout(300);
  await page_.screenshot({ path: outPngPath, type: 'png' });
}

async function renderComposedPage(
  page_: PlaywrightPage,
  htmlContent: string,
  outJpgPath: string,
  { width = 1600, height = 1000 } = {},
): Promise<void> {
  const tmpHtml = path.join(TMP_DIR, `compose-${crypto.randomUUID()}.html`);
  fs.writeFileSync(tmpHtml, htmlContent, 'utf8');
  await page_.setViewportSize({ width, height });
  await page_.goto(pathToFileURL(tmpHtml).href, { waitUntil: 'load', timeout: 15000 });
  await page_.waitForTimeout(120);
  await page_.screenshot({ path: outJpgPath, type: 'jpeg', quality: 90 });
}

// ---------------------------------------------------------------------------
// Per-item processors — each returns { outcome: 'processed' | 'fallback', html }
// ---------------------------------------------------------------------------

type ProcessResult = {
  outcome: 'processed' | 'fallback';
  html: string;
  galleryTiles?: string[];
  sheetGrid?: { cols: number; rows: number; totalTiles: number };
};

async function processKitSheet(pageObj: PlaywrightPage, item: CatalogItem, dir: string): Promise<ProcessResult> {
  let screens: string[] = [];
  let captionNote: string | null = null;

  const htmls = findHtmlCandidates(dir).slice(0, 7);
  if (htmls.length) {
    const rendered: { tmpPng: string; size: number }[] = [];
    for (const h of htmls) {
      const tmpPng = path.join(TMP_DIR, `html-${crypto.randomUUID()}.png`);
      try {
        await screenshotHtmlFile(pageObj, h, tmpPng);
        const size = fs.statSync(tmpPng).size;
        rendered.push({ tmpPng, size });
      } catch {
        // skip this page, try the next candidate
      }
    }
    // A near-empty/pre-animation capture compresses to a much smaller PNG
    // than a busy real page, so ranking by rendered file size is a cheap,
    // reliable proxy for "this frame actually shows content" — use it to
    // pick the hero rather than trusting filename order alone.
    rendered.sort((a, b) => b.size - a.size);
    for (const r of rendered.slice(0, 5)) {
      const uri = toDataUri(r.tmpPng);
      if (uri) screens.push(uri);
    }
  }

  // A bundled raster living next to the asset (Preview/cover.png and
  // similar) is a real export of the kit's own screens, sized for exactly
  // this purpose. A .fig's embedded thumbnail.png is Figma's incidental
  // canvas-navigator render, capped around 400px on its long edge regardless
  // of source size (see MIN_TILE_DIM below) — worse by construction whenever
  // a bundled raster exists. Try the bundled raster tier first so it outranks
  // the fig thumbnail rather than only being reached when the fig extraction
  // fails outright.
  if (screens.length === 0) {
    const rasters = findRasterCandidates(dir).slice(0, 5);
    for (const r of rasters) {
      const uri = toDataUri(r.path);
      if (uri) screens.push(uri);
      if (screens.length >= 5) break;
    }
  }

  if (screens.length === 0) {
    const figs = findFigFiles(dir);
    if (figs.length) {
      const firstFig = figs[0];
      const thumb = firstFig ? extractFigThumbnail(firstFig.path) : null;
      if (thumb) {
        // A many-frame .fig's embedded thumbnail.png is Figma's render of
        // the WHOLE canvas — for a kit with dozens of screens that IS a
        // contact sheet. Only check kits the curated description (or a
        // manually-verified id) already confirms are dense: see
        // looksLikeDenseSheet's comment for why pixel analysis alone is not
        // trusted as the primary signal here.
        if (looksLikeDenseSheet(item)) {
          const remediation = await tryRemediateContactSheet(pageObj, thumb);
          if (remediation) {
            return {
              outcome: 'processed',
              html: composeKitSheetHtml({
                label: item.label,
                categoryLabel: categoryLabelFor(item.category),
                screens: remediation.screens,
                captionNote: remediation.captionNote,
              }),
              galleryTiles: remediation.galleryTiles,
              sheetGrid: remediation.grid,
            };
          }
          // Confirmed dense sheet, but the embedded thumbnail has no tile
          // resolution worth slicing (MIN_TILE_DIM) or no clean grid was
          // found. Using the whole tiny grid as a single hero is exactly
          // the "tiny blurry contact sheet" this exists to avoid — a clean
          // typographic cover beats a bad image.
          return { outcome: 'fallback', html: composeFallbackFor(item, dir) };
        }
        // Single-thumbnail hero path: apply the same MIN_TILE_DIM floor the
        // sliced-tile path already enforces. A sub-floor thumbnail blown up
        // to fill the hero frame is exactly the "blurry cover" this script
        // exists to avoid — a clean typographic fallback beats it.
        const dims = getImagePixelDimensions(thumb);
        const meetsFloor = dims !== null && dims.width >= MIN_TILE_DIM && dims.height >= MIN_TILE_DIM;
        if (meetsFloor) {
          const uri = toDataUri(thumb);
          if (uri) {
            screens = [uri];
            captionNote = 'Figma design file';
          }
        }
      }
    }
  }

  if (screens.length === 0) {
    return { outcome: 'fallback', html: composeFallbackFor(item, dir) };
  }

  const html = composeKitSheetHtml({
    label: item.label,
    categoryLabel: categoryLabelFor(item.category),
    screens,
    captionNote,
  });
  return { outcome: 'processed', html };
}

async function processIconGrid(item: CatalogItem, dir: string): Promise<ProcessResult> {
  const allSvg = walkFiles(dir, { maxFiles: 8000 })
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .filter((f) => !/preview|iconjar|editables[_-]?figma[_-]?sketch/i.test(f));
  const allPng = walkFiles(dir, { maxFiles: 8000 })
    .filter((f) => f.toLowerCase().endsWith('.png'))
    .filter((f) => !/preview/i.test(f));
  const pool = allSvg.length ? allSvg : allPng;
  if (!pool.length) return { outcome: 'fallback', html: composeFallbackFor(item, dir) };

  const byDir = new Map<string, string[]>();
  for (const f of pool) {
    const d = path.dirname(f);
    const arr = byDir.get(d);
    if (arr) {
      arr.push(f);
    } else {
      byDir.set(d, [f]);
    }
  }
  const dirs = [...byDir.keys()];

  const total = pool.length;
  let target = total;
  let cols = Math.min(5, total);
  let rows = Math.ceil(total / cols);
  if (total >= 32) {
    target = 32;
    cols = 8;
    rows = 4;
  } else if (total >= 24) {
    target = 24;
    cols = 6;
    rows = 4;
  } else if (total >= 15) {
    target = 15;
    cols = 5;
    rows = 3;
  }

  const picked: string[] = [];
  while (picked.length < target) {
    let progressed = false;
    for (const d of dirs) {
      const arr = byDir.get(d);
      if (arr && arr.length) {
        const next = arr.shift();
        if (next !== undefined) {
          picked.push(next);
          progressed = true;
        }
      }
      if (picked.length >= target) break;
    }
    if (!progressed) break;
  }

  const icons: IconCell[] = [];
  for (const f of picked) {
    if (f.toLowerCase().endsWith('.svg')) {
      const svg = readSvgInline(f);
      if (svg) icons.push({ svg });
    } else {
      const uri = toDataUri(f, { maxDim: 200 });
      if (uri) icons.push({ dataUri: uri });
    }
  }
  if (!icons.length) return { outcome: 'fallback', html: composeFallbackFor(item, dir) };

  const html = composeIconGridHtml({
    label: item.label,
    categoryLabel: categoryLabelFor(item.category),
    icons,
    cols,
    rows,
  });
  return { outcome: 'processed', html };
}

async function processMissingOther(pageObj: PlaywrightPage, item: CatalogItem, dir: string): Promise<ProcessResult> {
  const htmls = findHtmlCandidates(dir);
  if (htmls.length) {
    const firstHtml = htmls[0];
    const tmpPng = path.join(TMP_DIR, `html-${crypto.randomUUID()}.png`);
    try {
      if (firstHtml) {
        await screenshotHtmlFile(pageObj, firstHtml, tmpPng, { width: 1600, height: 1000 });
        const uri = toDataUri(tmpPng, { maxDim: 1400 });
        if (uri) {
          return {
            outcome: 'processed',
            html: composeHeroCoverHtml({ label: item.label, categoryLabel: categoryLabelFor(item.category), dataUri: uri }),
          };
        }
      }
    } catch {
      // fall through to other strategies
    }
  }

  const rasters = findRasterCandidates(dir);
  const firstRaster = rasters[0];
  if (firstRaster) {
    const uri = toDataUri(firstRaster.path, { maxDim: 1400 });
    if (uri) {
      return {
        outcome: 'processed',
        html: composeHeroCoverHtml({ label: item.label, categoryLabel: categoryLabelFor(item.category), dataUri: uri }),
      };
    }
  }

  const zips = findZipFiles(dir);
  const firstZip = zips[0];
  if (firstZip) {
    const img = extractBestImageFromZip(firstZip.path);
    if (img) {
      const uri = toDataUri(img, { maxDim: 1400 });
      if (uri) {
        return {
          outcome: 'processed',
          html: composeHeroCoverHtml({ label: item.label, categoryLabel: categoryLabelFor(item.category), dataUri: uri }),
        };
      }
    }
  }

  return { outcome: 'fallback', html: composeFallbackFor(item, dir) };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function isMissing(item: CatalogItem): boolean {
  if (item.cover_policy) return false;
  if (!item.thumb) return true;
  return !fs.existsSync(path.join(ASSETS_ROOT, item.thumb));
}

type CategoryCounts = { processed: number; fallback: number; skipped: number; error: number };

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  let onlyFilter: string | null = null;
  const onlyIdx = args.indexOf('--only');
  if (onlyIdx !== -1) onlyFilter = args[onlyIdx + 1] ?? null;

  fs.mkdirSync(THUMBS_DIR, { recursive: true });
  fs.mkdirSync(META_DIR, { recursive: true });
  fs.mkdirSync(BACKUP_DIR, { recursive: true });

  const raw = fs.readFileSync(CATALOG_PATH, 'utf8');
  const data = JSON.parse(raw) as CatalogData;

  if (!fs.existsSync(BACKUP_PATH)) {
    fs.writeFileSync(BACKUP_PATH, raw);
    console.log(`Backed up catalog.json -> ${BACKUP_PATH}`);
  } else {
    console.log(`Backup already exists at ${BACKUP_PATH} (not overwritten)`);
  }

  const allItems: CatalogItem[] = [];
  for (const group of data.groups ?? []) {
    for (const item of group.items ?? []) allItems.push(item);
  }

  // cover_policy items are exempt from this generator entirely — the kit/icon
  // category sweep must not overwrite a policy-protected cover.
  let scope = allItems.filter(
    (it) => !it.cover_policy && (KIT_CATEGORIES.has(it.category) || it.category === 'icons' || isMissing(it)),
  );
  if (onlyFilter) {
    scope = scope.filter((it) => it.category === onlyFilter || it.id === onlyFilter);
  }
  console.log(`Scope: ${scope.length} item(s)`);

  const browser = await chromium.launch();
  const pageObj = await browser.newPage();

  const counts: Record<string, CategoryCounts> = {};
  let changed = false;
  const remediatedSheets: { id: string; cols: number; rows: number; totalTiles: number; galleryCount: number }[] = [];

  for (const item of scope) {
    const cat = item.category || '(none)';
    counts[cat] ??= { processed: 0, fallback: 0, skipped: 0, error: 0 };
    const catCounts = counts[cat];

    const metaPath = path.join(META_DIR, `${item.id}.json`);
    const outJpg = path.join(THUMBS_DIR, `${item.id}.jpg`);
    if (fs.existsSync(metaPath) && fs.existsSync(outJpg)) {
      // Render is already done, but catalog.json's thumb field may not point
      // at it — e.g. a crash between writing the jpg and patching the
      // catalog, or a future catalog regen that dropped the field. Relink
      // rather than silently leaving a stale/null thumb.
      const relThumb = path.relative(ASSETS_ROOT, outJpg);
      if (item.thumb !== relThumb) {
        item.thumb = relThumb;
        changed = true;
      }
      catCounts.skipped += 1;
      continue;
    }

    const dir = path.join(ASSETS_ROOT, item.rel);
    if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
      catCounts.error += 1;
      console.warn(`  ! missing item directory for ${item.id}: ${item.rel}`);
      continue;
    }

    try {
      let result: ProcessResult;
      if (item.category === 'icons') {
        result = await processIconGrid(item, dir);
      } else if (KIT_CATEGORIES.has(item.category)) {
        result = await processKitSheet(pageObj, item, dir);
      } else {
        result = await processMissingOther(pageObj, item, dir);
      }

      await renderComposedPage(pageObj, result.html, outJpg);

      let galleryCount = 0;
      if (result.galleryTiles?.length) {
        for (let i = 0; i < result.galleryTiles.length && i < 4; i++) {
          const tileUri = result.galleryTiles[i];
          if (!tileUri) continue;
          const tilePath = path.join(THUMBS_DIR, `${item.id}-tile-${i + 1}.jpg`);
          if (writeDataUriToFile(tileUri, tilePath)) galleryCount++;
        }
      }
      if (result.sheetGrid) {
        remediatedSheets.push({ id: item.id, ...result.sheetGrid, galleryCount });
      }

      fs.writeFileSync(
        metaPath,
        JSON.stringify(
          {
            category: item.category,
            outcome: result.outcome,
            generatedAt: new Date().toISOString(),
            ...(result.sheetGrid ? { sheetGrid: result.sheetGrid, galleryTiles: galleryCount } : {}),
          },
          null,
          2,
        ),
      );

      const relThumb = path.relative(ASSETS_ROOT, outJpg);
      if (item.thumb !== relThumb) {
        item.thumb = relThumb;
        changed = true;
      }
      catCounts[result.outcome === 'fallback' ? 'fallback' : 'processed'] += 1;
      const sheetNote = result.sheetGrid ? ` (sliced ${result.sheetGrid.cols}x${result.sheetGrid.rows} sheet, ${galleryCount} gallery tiles)` : '';
      console.log(`  ${result.outcome === 'fallback' ? '[fallback] ' : '[ok]       '}${item.id}${sheetNote}`);
    } catch (err) {
      catCounts.error += 1;
      console.warn(`  ! error on ${item.id}: ${errorMessage(err)}`);
    }
  }

  await browser.close();
  fs.rmSync(TMP_DIR, { recursive: true, force: true });

  if (changed) {
    fs.writeFileSync(CATALOG_PATH, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
    console.log('catalog.json updated (thumb fields only).');
  } else {
    console.log('catalog.json unchanged (nothing new to write).');
  }

  console.log('\nSummary:');
  console.log(
    'category'.padEnd(16),
    'processed'.padEnd(10),
    'fallback-typographic'.padEnd(22),
    'skipped-ok'.padEnd(12),
    'error',
  );
  const totals: CategoryCounts = { processed: 0, fallback: 0, skipped: 0, error: 0 };
  for (const [catName, c] of Object.entries(counts)) {
    console.log(catName.padEnd(16), String(c.processed).padEnd(10), String(c.fallback).padEnd(22), String(c.skipped).padEnd(12), String(c.error));
    totals.processed += c.processed;
    totals.fallback += c.fallback;
    totals.skipped += c.skipped;
    totals.error += c.error;
  }
  console.log(
    'TOTAL'.padEnd(16),
    String(totals.processed).padEnd(10),
    String(totals.fallback).padEnd(22),
    String(totals.skipped).padEnd(12),
    String(totals.error),
  );

  if (remediatedSheets.length) {
    console.log('\nContact-sheet remediation:');
    for (const s of remediatedSheets) {
      console.log(`  ${s.id}: ${s.cols}x${s.rows} grid (${s.totalTiles} tiles detected) -> ${s.galleryCount} gallery tiles`);
    }
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
