#!/usr/bin/env python3
import argparse, json, html, shutil
from pathlib import Path
from datetime import datetime

ROLES = [
    ("hook", "AI tools update every day, but the real question is not whether a feature exists", "Grab attention: the audience is already fatigued by feature lists."),
    ("conflict", "Feeding raw material straight into a PPT lets model noise land on the page", "Create tension: a pretty page is not a presentable structure."),
    ("method", "Humanize PPT first turns the material into an audience path with AST", "Explain the method: Audience, State, Transfer."),
    ("proof", "The same material can go through stable production, style exploration, presenter mode, and deploy", "Give evidence: the workflow is not a template collage."),
    ("takeaway", "Settle the content before the style; ship the deck before the talk track", "Close with a takeaway principle."),
]

STYLES = {
    "guizang-stable": {
        "label": "Stable / guizang-style",
        "bg": "#f6f1e8", "fg": "#171717", "accent": "#8b1e1e", "font": "-apple-system,BlinkMacSystemFont,sans-serif"
    },
    "zara-editorial": {
        "label": "Style Exploration / Zara Editorial",
        "bg": "#111111", "fg": "#f7f1e8", "accent": "#d7b56d", "font": "Georgia,'Times New Roman',serif"
    },
    "zara-contrast": {
        "label": "Style Exploration / Zara Contrast",
        "bg": "#fafafa", "fg": "#111111", "accent": "#ff4d00", "font": "Inter,-apple-system,BlinkMacSystemFont,sans-serif"
    },
}

def read_source(path):
    text = Path(path).read_text(encoding='utf-8')
    lines = [l.strip() for l in text.splitlines() if l.strip() and not l.startswith('#')]
    return text, lines

def make_plan(title, lines):
    plan=[]
    for i,(role,msg,intent) in enumerate(ROLES,1):
        evidence = lines[min(i-1, len(lines)-1)] if lines else msg
        plan.append({
            "slide_id": f"S{i:02d}",
            "role": role,
            "title": title if i == 1 else msg.split('.')[0],
            "message": msg,
            "visible_content": [msg, evidence[:90]],
            "speaker_intent": intent,
            "asset_need": "optional screenshot / simple flow diagram" if i in (3,4) else "none",
            "recommended_renderer": "guizang-stable or zara-style"
        })
    return plan

def write_contracts(out, title, plan):
    out.mkdir(parents=True, exist_ok=True)
    (out/'deck_brief.md').write_text(f"""# Deck Brief\n\n## Deck Goal\nExplain how Humanize PPT V0.1 turns raw material into a presentable, generatable, deployable PPT workflow.\n\n## Audience\nContent creators and independent developers interested in AI tools, PPT agents, and skill workflows.\n\n## Initial State\nAI PPT tools update constantly, but the updates read like feature lists.\n\n## Desired State\nThe value of Humanize PPT is directing the AST outline first, then handing off to a downstream skill.\n\n## Core Tension\nPretty pages vs presentable structure.\n\n## Success Criteria\nThe audience can restate: settle content before style; ship the deck before the talk track; keep deploy and presenter enhancement separate.\n""", encoding='utf-8')
    (out/'ast_outline.md').write_text(f"""# AST Outline\n\n## Audience\nHands-on AI tool testers, independent creators, and developers.\n\n## State\n- Initial: they assume PPT agents differ mainly in templates and visuals.\n- Desired: they realize the real upstream difference is the outline-director layer.\n\n## Transfer\n{chr(10).join([f"- {p['slide_id']} / {p['role']}: {p['speaker_intent']}" for p in plan])}\n""", encoding='utf-8')
    (out/'slide_plan.json').write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding='utf-8')
    (out/'speaker_intent.md').write_text('\n'.join([f"## {p['slide_id']} {p['title']}\n\n- Intent: {p['speaker_intent']}\n- Say: {p['message']}\n- Do not say: do not expand this into a tool list.\n" for p in plan]), encoding='utf-8')
    (out/'asset_manifest.md').write_text("# Asset Manifest\n\n| asset_id | type | purpose | status |\n|---|---|---|---|\n| flow-01 | diagram | OPC workflow diagram | generated by HTML/CSS |\n", encoding='utf-8')
    videos=[{"video_id":"V01","slide_id":"S04","purpose":"Show the dynamic path from AST outline to style exploration","duration_seconds":8,"aspect_ratio":"16:9","fallback_static":"flow-01"}]
    (out/'video_slots.json').write_text(json.dumps(videos, ensure_ascii=False, indent=2), encoding='utf-8')

def deck_html(title, plan, style_id, style):
    slides=[]
    for p in plan:
        bullets=''.join(f"<li>{html.escape(x)}</li>" for x in p['visible_content'])
        slides.append(f"""
<section class='slide' id='{p['slide_id']}'>
  <div class='kicker'>{html.escape(style['label'])} · {html.escape(p['role'])}</div>
  <h1>{html.escape(p['title'])}</h1>
  <p class='message'>{html.escape(p['message'])}</p>
  <ul>{bullets}</ul>
  <div class='footer'>{p['slide_id']} / Humanize PPT V0.1</div>
</section>""")
    return f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{html.escape(title)} · {style_id}</title>
<style>
:root{{--bg:{style['bg']};--fg:{style['fg']};--accent:{style['accent']};--font:{style['font']};}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--fg);font-family:var(--font);overflow:hidden}} .slide{{display:none;width:100vw;height:100vh;padding:7vh 8vw;position:relative}} .slide.active{{display:block}} .kicker{{color:var(--accent);font-weight:700;letter-spacing:.08em;text-transform:uppercase}} h1{{font-size:clamp(42px,7vw,104px);line-height:1.02;margin:5vh 0 3vh;max-width:1100px}} .message{{font-size:clamp(22px,2.6vw,38px);line-height:1.35;max-width:980px}} ul{{font-size:clamp(18px,1.6vw,28px);line-height:1.6;max-width:1000px;margin-top:5vh}} .footer{{position:absolute;left:8vw;bottom:5vh;color:var(--accent)}} .nav{{position:fixed;right:24px;bottom:20px;font:16px system-ui;color:var(--fg);opacity:.7}}
</style></head><body>
{''.join(slides)}
<div class='nav'>← / → to navigate</div>
<script>
const slides=[...document.querySelectorAll('.slide')];let i=Number(new URLSearchParams(location.search).get('slide')||0);function show(n){{i=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,k)=>s.classList.toggle('active',k===i));location.hash='slide-'+(i+1);window.parent&&window.parent.postMessage({{type:'humanize-slide',index:i,total:slides.length}},'*')}}
document.addEventListener('keydown',e=>{{if(e.key==='ArrowRight'||e.key===' ')show(i+1);if(e.key==='ArrowLeft')show(i-1)}});show(i);
</script></body></html>"""

def write_styles(out, title, plan):
    styles_dir=out/'styles'; styles_dir.mkdir(exist_ok=True)
    cards=[]
    for sid,style in STYLES.items():
        (styles_dir/f'{sid}.html').write_text(deck_html(title, plan, sid, style), encoding='utf-8')
        cards.append(f"<a class='card' href='{sid}.html'><b>{style['label']}</b><span>{sid}</span></a>")
    index=f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><title>Style Exploration</title><style>body{{font-family:-apple-system,BlinkMacSystemFont,sans-serif;margin:40px;background:#f6f3ee}}h1{{font-size:48px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}}.card{{display:block;padding:28px;border:1px solid #ddd;border-radius:20px;background:white;color:#111;text-decoration:none}}.card b{{display:block;font-size:24px;margin-bottom:12px}}.card span{{color:#777}}</style></head><body><h1>Humanize PPT Style Exploration</h1><p>Generate 3 directions from the AST outline first; enter presenter / deploy once one is chosen.</p><div class='grid'>{''.join(cards)}</div></body></html>"""
    (styles_dir/'index.html').write_text(index, encoding='utf-8')

def write_presenter(out, title, plan, selected='zara-editorial'):
    pres=out/'presenter'; pres.mkdir(exist_ok=True)
    notes=[{"slide_id":p['slide_id'],"title":p['title'],"note":p['speaker_intent'],"say":p['message']} for p in plan]
    (pres/'notes.json').write_text(json.dumps(notes, ensure_ascii=False, indent=2), encoding='utf-8')
    deck_src=f"../styles/{selected}.html"
    next_src=f"../styles/{selected}.html?slide=1"
    html_doc=f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><title>{html.escape(title)} · Presenter</title><style>body{{margin:0;background:#0d0d0d;color:#f8f8f8;font-family:-apple-system,BlinkMacSystemFont,sans-serif}}.wrap{{display:grid;grid-template-columns:2fr 1fr;height:100vh;gap:16px;padding:16px}}iframe{{width:100%;height:100%;border:0;border-radius:16px;background:white}}.side{{display:grid;grid-template-rows:1fr 1fr 1fr;gap:16px}}.panel{{background:#1b1b1b;border:1px solid #333;border-radius:16px;padding:18px;overflow:auto}}h2{{margin:0 0 12px}}.note{{font-size:22px;line-height:1.45}}button{{font-size:18px;padding:10px 14px;margin-right:8px;border-radius:10px;border:0}}</style></head><body><div class='wrap'><iframe id='current' src='{deck_src}'></iframe><div class='side'><div class='panel'><h2>Next slide</h2><iframe id='next' src='{next_src}'></iframe></div><div class='panel'><h2>Speaker Notes</h2><div id='note' class='note'></div></div><div class='panel'><h2>Controls</h2><p id='timer'>00:00</p><button onclick='go(-1)'>Prev</button><button onclick='go(1)'>Next</button></div></div></div><script>const notes={json.dumps(notes, ensure_ascii=False)};let i=0,t=Date.now();function sync(){{document.getElementById('current').src='{deck_src}?slide='+i;document.getElementById('next').src='{deck_src}?slide='+Math.min(i+1,notes.length-1);document.getElementById('note').innerHTML='<b>'+notes[i].slide_id+' '+notes[i].title+'</b><br>'+notes[i].note+'<hr>'+notes[i].say}}function go(d){{i=Math.max(0,Math.min(notes.length-1,i+d));sync()}}document.addEventListener('keydown',e=>{{if(e.key==='ArrowRight'||e.key===' ')go(1);if(e.key==='ArrowLeft')go(-1)}});setInterval(()=>{{let s=Math.floor((Date.now()-t)/1000);document.getElementById('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}},500);sync();</script></body></html>"""
    (pres/'index.html').write_text(html_doc, encoding='utf-8')

def write_deploy(out):
    dep=out/'deploy'; dep.mkdir(exist_ok=True)
    shutil.copytree(out/'styles', dep/'styles', dirs_exist_ok=True)
    shutil.copytree(out/'presenter', dep/'presenter', dirs_exist_ok=True)
    (dep/'index.html').write_text("<meta charset='utf-8'><h1>Humanize PPT Deploy Package</h1><ul><li><a href='styles/index.html'>Style Exploration</a></li><li><a href='presenter/index.html'>Presenter Mode</a></li></ul>", encoding='utf-8')
    (dep/'presenter.html').write_text("<meta http-equiv='refresh' content='0; url=presenter/index.html'>", encoding='utf-8')

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--source', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--title', default='Humanize PPT Demo')
    args=ap.parse_args()
    out=Path(args.out)
    text, lines=read_source(args.source)
    plan=make_plan(args.title, lines)
    write_contracts(out, args.title, plan)
    write_styles(out, args.title, plan)
    write_presenter(out, args.title, plan)
    write_deploy(out)
    print(json.dumps({"ok": True, "out": str(out), "style_index": str(out/'styles'/'index.html'), "presenter": str(out/'presenter'/'index.html'), "deploy": str(out/'deploy'/'index.html')}, ensure_ascii=False, indent=2))
if __name__ == '__main__': main()
