// F-01 (W7A) upload fixture manifest, owned by 7A. 7C/7D do not edit this
// file this wave; their fixtures live under their own daemon test
// directories. Bytes are never committed as binaries —
// `w7-upload-fixture-bytes.ts` regenerates the exact same content at test
// time from `sizeBytes`, and `sha256` here pins that content so a spec can
// verify what it received matches what it sent.
//
// A TypeScript module, not JSON: `e2e/resources/` files must be flat
// TypeScript (`scripts/guard.ts`'s E2E package layout check).

export interface W7UploadManifestRow {
  id: string;
  description: string;
  sizeBytes: number;
  sha256: string;
  generatorCommand: string;
}

export interface W7UploadManifest {
  note: string;
  generatorScript: string;
  extension: string;
  mime: string;
  testLimitOverrideBytes: number;
  testLimitOverrideEnvVar: string;
  rows: W7UploadManifestRow[];
}

export const w7UploadManifest: W7UploadManifest = {
  note:
    'F-01 (W7A) upload fixture manifest, owned by 7A. 7C/7D do not edit this file this wave; their '
    + 'fixtures live under their own daemon test directories. Bytes are never committed as binaries — '
    + '`w7-upload-fixture-bytes.ts` regenerates the exact same content at test time from `sizeBytes`, '
    + 'and `sha256` here pins that content so a spec can verify what it received matches what it sent.',
  generatorScript: 'e2e/resources/w7-upload-fixture-bytes.ts',
  extension: 'txt',
  mime: 'text/plain',
  testLimitOverrideBytes: 2_097_152,
  testLimitOverrideEnvVar: 'OD_UPLOAD_MAX_FILE_BYTES',
  rows: [
    {
      id: 'small-1mib',
      description: '1 MiB — well under the test suite\'s overridden limit',
      sizeBytes: 1_048_576,
      sha256: '2fa5c0a923bd7c755a194fc1bac343714c1396ada67905346f0b0ba715c2b9df',
      generatorCommand:
        'node --experimental-strip-types -e "import(\'./w7-upload-fixture-bytes.ts\').then(m => '
        + 'require(\'node:crypto\').createHash(\'sha256\').update(m.generateUploadFixtureBytes(1048576))'
        + '.digest(\'hex\')).then(console.log)"',
    },
    {
      id: 'at-limit',
      description: 'exactly testLimitOverrideBytes — must be accepted',
      sizeBytes: 2_097_152,
      sha256: '44a8e2e1743d6cc724e606961a2b347cc3c0a2250cab482ddf8b424feba2dde5',
      generatorCommand:
        'node --experimental-strip-types -e "import(\'./w7-upload-fixture-bytes.ts\').then(m => '
        + 'require(\'node:crypto\').createHash(\'sha256\').update(m.generateUploadFixtureBytes(2097152))'
        + '.digest(\'hex\')).then(console.log)"',
    },
    {
      id: 'over-limit',
      description: 'testLimitOverrideBytes + 1 byte — must be rejected 413, the error naming the limit',
      sizeBytes: 2_097_153,
      sha256: '9238d69ea22b02d5a539338ce5230fa07491c696ebd0af14edc4885bc9cdc15e',
      generatorCommand:
        'node --experimental-strip-types -e "import(\'./w7-upload-fixture-bytes.ts\').then(m => '
        + 'require(\'node:crypto\').createHash(\'sha256\').update(m.generateUploadFixtureBytes(2097153))'
        + '.digest(\'hex\')).then(console.log)"',
    },
    {
      id: 'midsize-64mib',
      description:
        '64 MiB — large enough that a throttled transfer exposes multiple distinct progress events '
        + 'and a real mid-transfer window',
      sizeBytes: 67_108_864,
      sha256: 'e599d773a30346d9826dba4035fbb3e9649c8015bd0f0bc8cc3443591d70ef22',
      generatorCommand:
        'node --experimental-strip-types -e "import(\'./w7-upload-fixture-bytes.ts\').then(m => '
        + 'require(\'node:crypto\').createHash(\'sha256\').update(m.generateUploadFixtureBytes(67108864))'
        + '.digest(\'hex\')).then(console.log)"',
    },
  ],
};
